# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://captv89.github.io
baseurl: /galley-news
title: My Blog
description: "The Galley News"
keywords: 'mariner,sailor,diary,blog'

home:
  section1: <h1>Galley News</h1>
  section2: <h2>My Blogs.. in other words 'The Galley News !'</h2>
blog:
  
disqus:
  shortname: captv89
  public_key: 3cXZ9tFXeGZRMEFB1exWbQQOeA6zXMXLngJd9oOaGVgZf8wxf4D5TlMr5QiAk3iC
google_analytics: UA-113341784-1
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5 

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
